// lib/audit/questions.ts
// Base de données des questions d'audit AI Act - 150+ questions intelligentes

export interface QuestionOption {
  label: string;
  value: string;
  score: number;
  riskLevel?: "low" | "medium" | "high" | "critical";
  triggerQuestions?: string[]; // IDs des questions à afficher si cette option est choisie
}

export interface Question {
  id: string;
  category: string;
  subcategory: string;
  question: string;
  description?: string;
  type: "single" | "multiple" | "text" | "number" | "scale";
  options?: QuestionOption[];
  required: boolean;
  forPlans: ("starter" | "pro" | "enterprise")[];
  forSectors?: string[]; // Si vide = tous les secteurs
  forSizes?: string[]; // Si vide = toutes les tailles
  conditions?: { questionId: string; values: string[] }[]; // Afficher si ces conditions sont remplies
  weight: number; // Importance pour le score (1-10)
  aiActArticle?: string; // Article AI Act concerné
  collectData?: string; // Nom du champ à collecter pour templates
}

// Secteurs d'activité
export const SECTORS = [
  { id: "finance", name: "Finance / Banque / Assurance", highRisk: true },
  { id: "health", name: "Santé / Médical / Pharma", highRisk: true },
  { id: "hr", name: "Ressources Humaines / Recrutement", highRisk: true },
  { id: "legal", name: "Juridique / Justice", highRisk: true },
  { id: "education", name: "Éducation / Formation", highRisk: true },
  { id: "public", name: "Secteur Public / Administration", highRisk: true },
  { id: "retail", name: "Commerce / Retail / E-commerce", highRisk: false },
  { id: "industry", name: "Industrie / Manufacturing", highRisk: false },
  { id: "tech", name: "Tech / IT / Digital", highRisk: false },
  { id: "services", name: "Services aux entreprises", highRisk: false },
  { id: "transport", name: "Transport / Logistique", highRisk: false },
  { id: "energy", name: "Énergie / Utilities", highRisk: false },
  { id: "media", name: "Média / Communication / Marketing", highRisk: false },
  { id: "other", name: "Autre secteur", highRisk: false },
];

// Tailles d'entreprise
export const COMPANY_SIZES = [
  { id: "tpe", name: "TPE (1-10 salariés)", employees: "1-10" },
  { id: "pme", name: "PME (11-250 salariés)", employees: "11-250" },
  { id: "eti", name: "ETI (251-5000 salariés)", employees: "251-5000" },
  { id: "ge", name: "Grande Entreprise (5000+ salariés)", employees: "5000+" },
];

// Catégories de questions
export const CATEGORIES = [
  {
    id: "company_profile",
    name: "Profil de l'entreprise",
    icon: "🏢",
    color: "#00F5FF",
    description: "Informations générales sur votre organisation",
  },
  {
    id: "ai_inventory",
    name: "Inventaire des systèmes IA",
    icon: "📋",
    color: "#8B5CF6",
    description: "Recensement de tous vos outils utilisant l'IA",
  },
  {
    id: "risk_classification",
    name: "Classification des risques",
    icon: "⚠️",
    color: "#FF6B00",
    description: "Évaluation du niveau de risque de vos systèmes",
  },
  {
    id: "governance",
    name: "Gouvernance IA",
    icon: "🏛️",
    color: "#00FF88",
    description: "Organisation et politique d'utilisation de l'IA",
  },
  {
    id: "documentation",
    name: "Documentation technique",
    icon: "📄",
    color: "#FFB800",
    description: "Traçabilité et documentation des systèmes",
  },
  {
    id: "training",
    name: "Formation et compétences",
    icon: "🎓",
    color: "#FF4444",
    description: "Niveau de connaissance de vos équipes",
  },
  {
    id: "data_management",
    name: "Gestion des données",
    icon: "💾",
    color: "#00B4D8",
    description: "Qualité et gouvernance des données IA",
  },
  {
    id: "transparency",
    name: "Transparence et information",
    icon: "👁️",
    color: "#E040FB",
    description: "Communication sur l'utilisation de l'IA",
  },
  {
    id: "human_oversight",
    name: "Supervision humaine",
    icon: "👤",
    color: "#FF7043",
    description: "Contrôle humain des décisions IA",
  },
  {
    id: "security",
    name: "Sécurité et robustesse",
    icon: "🔒",
    color: "#26A69A",
    description: "Protection et fiabilité des systèmes",
  },
  {
    id: "compliance_process",
    name: "Processus de conformité",
    icon: "✅",
    color: "#66BB6A",
    description: "Démarches et organisation pour la conformité",
  },
  {
    id: "suppliers",
    name: "Fournisseurs et sous-traitants",
    icon: "🤝",
    color: "#AB47BC",
    description: "Gestion des prestataires IA",
  },
];

// Les 150+ questions
export const QUESTIONS: Question[] = [
  // ============================================
  // PROFIL ENTREPRISE (10 questions)
  // ============================================
  {
    id: "company_name",
    category: "company_profile",
    subcategory: "Identification",
    question: "Quel est le nom de votre entreprise ?",
    type: "text",
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 1,
    collectData: "companyName",
  },
  {
    id: "company_sector",
    category: "company_profile",
    subcategory: "Identification",
    question: "Dans quel secteur d'activité exercez-vous ?",
    description: "Cette information permet d'adapter les questions à votre contexte réglementaire spécifique.",
    type: "single",
    options: SECTORS.map(s => ({ label: s.name, value: s.id, score: s.highRisk ? 2 : 0 })),
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 8,
    collectData: "sector",
  },
  {
    id: "company_size",
    category: "company_profile",
    subcategory: "Identification",
    question: "Quelle est la taille de votre entreprise ?",
    type: "single",
    options: COMPANY_SIZES.map(s => ({ label: s.name, value: s.id, score: 0 })),
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 5,
    collectData: "companySize",
  },
  {
    id: "company_revenue",
    category: "company_profile",
    subcategory: "Identification",
    question: "Quel est votre chiffre d'affaires annuel approximatif ?",
    type: "single",
    options: [
      { label: "Moins de 1M€", value: "under_1m", score: 0 },
      { label: "1M€ - 10M€", value: "1m_10m", score: 0 },
      { label: "10M€ - 50M€", value: "10m_50m", score: 1 },
      { label: "50M€ - 250M€", value: "50m_250m", score: 2 },
      { label: "Plus de 250M€", value: "over_250m", score: 3 },
    ],
    required: true,
    forPlans: ["pro", "enterprise"],
    weight: 3,
    collectData: "revenue",
  },
  {
    id: "company_international",
    category: "company_profile",
    subcategory: "Identification",
    question: "Avez-vous des activités dans plusieurs pays de l'UE ?",
    type: "single",
    options: [
      { label: "Non, uniquement en France", value: "france_only", score: 0 },
      { label: "Oui, dans 2-5 pays", value: "few_countries", score: 1 },
      { label: "Oui, dans plus de 5 pays", value: "many_countries", score: 2 },
    ],
    required: true,
    forPlans: ["pro", "enterprise"],
    weight: 4,
    collectData: "international",
  },
  {
    id: "company_b2b_b2c",
    category: "company_profile",
    subcategory: "Activité",
    question: "Votre activité est principalement :",
    type: "single",
    options: [
      { label: "B2B (clients professionnels)", value: "b2b", score: 0 },
      { label: "B2C (clients particuliers)", value: "b2c", score: 2 },
      { label: "Les deux", value: "both", score: 1 },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 5,
  },
  {
    id: "company_regulated",
    category: "company_profile",
    subcategory: "Activité",
    question: "Êtes-vous soumis à des réglementations sectorielles spécifiques ?",
    description: "Ex: RGPD renforcé santé, réglementation bancaire, etc.",
    type: "multiple",
    options: [
      { label: "Réglementation bancaire (DSP2, Bâle III...)", value: "banking", score: 2 },
      { label: "Réglementation santé (HDS, RGPD santé...)", value: "health", score: 2 },
      { label: "Réglementation assurance (Solvabilité II...)", value: "insurance", score: 2 },
      { label: "RGPD classique uniquement", value: "gdpr_only", score: 1 },
      { label: "Aucune réglementation spécifique", value: "none", score: 0 },
    ],
    required: true,
    forPlans: ["pro", "enterprise"],
    weight: 6,
  },
  {
    id: "company_dpo",
    category: "company_profile",
    subcategory: "Organisation",
    question: "Avez-vous un DPO (Délégué à la Protection des Données) ?",
    type: "single",
    options: [
      { label: "Oui, en interne", value: "internal", score: 0 },
      { label: "Oui, externalisé", value: "external", score: 1 },
      { label: "Non", value: "no", score: 3 },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 6,
  },
  {
    id: "company_it_team",
    category: "company_profile",
    subcategory: "Organisation",
    question: "Disposez-vous d'une équipe IT/DSI en interne ?",
    type: "single",
    options: [
      { label: "Oui, équipe dédiée (5+ personnes)", value: "large_team", score: 0 },
      { label: "Oui, petite équipe (1-4 personnes)", value: "small_team", score: 1 },
      { label: "Non, tout est externalisé", value: "outsourced", score: 2 },
    ],
    required: true,
    forPlans: ["pro", "enterprise"],
    weight: 4,
  },
  {
    id: "company_ai_budget",
    category: "company_profile",
    subcategory: "Organisation",
    question: "Quel budget annuel consacrez-vous aux outils numériques/IA ?",
    type: "single",
    options: [
      { label: "Moins de 10 000€", value: "under_10k", score: 0 },
      { label: "10 000€ - 50 000€", value: "10k_50k", score: 0 },
      { label: "50 000€ - 200 000€", value: "50k_200k", score: 1 },
      { label: "Plus de 200 000€", value: "over_200k", score: 2 },
    ],
    required: false,
    forPlans: ["enterprise"],
    weight: 3,
  },

  // ============================================
  // INVENTAIRE IA (25 questions)
  // ============================================
  {
    id: "ai_inventory_exists",
    category: "ai_inventory",
    subcategory: "Recensement",
    question: "Avez-vous réalisé un inventaire de tous les systèmes d'IA utilisés dans votre entreprise ?",
    type: "single",
    options: [
      { label: "Oui, inventaire complet et à jour", value: "complete", score: 0 },
      { label: "Oui, mais partiel ou pas à jour", value: "partial", score: 2 },
      { label: "Non, pas d'inventaire", value: "no", score: 4 },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 9,
    aiActArticle: "Article 6 - Classification",
  },
  {
    id: "ai_count",
    category: "ai_inventory",
    subcategory: "Recensement",
    question: "Combien de systèmes ou outils utilisant l'IA sont utilisés dans votre entreprise ?",
    type: "single",
    options: [
      { label: "1-5 systèmes", value: "1_5", score: 0 },
      { label: "6-15 systèmes", value: "6_15", score: 1 },
      { label: "16-50 systèmes", value: "16_50", score: 2 },
      { label: "Plus de 50 systèmes", value: "50_plus", score: 3 },
      { label: "Je ne sais pas", value: "unknown", score: 4 },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 7,
    collectData: "aiSystemsCount",
  },
  {
    id: "ai_genai_usage",
    category: "ai_inventory",
    subcategory: "IA Générative",
    question: "Utilisez-vous des outils d'IA générative (ChatGPT, Claude, Copilot, Midjourney...) ?",
    type: "single",
    options: [
      { label: "Non, pas d'IA générative", value: "no", score: 0 },
      { label: "Oui, avec une politique encadrée", value: "yes_policy", score: 1 },
      { label: "Oui, usage libre sans encadrement", value: "yes_free", score: 3 },
      { label: "Je ne sais pas", value: "unknown", score: 4 },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 8,
    aiActArticle: "Article 50 - Transparence GPAI",
  },
  {
    id: "ai_genai_list",
    category: "ai_inventory",
    subcategory: "IA Générative",
    question: "Quels outils d'IA générative utilisez-vous ?",
    description: "Sélectionnez tous les outils utilisés dans votre organisation.",
    type: "multiple",
    options: [
      { label: "ChatGPT / OpenAI", value: "chatgpt", score: 1 },
      { label: "Claude / Anthropic", value: "claude", score: 1 },
      { label: "Microsoft Copilot", value: "copilot", score: 1 },
      { label: "Google Gemini / Bard", value: "gemini", score: 1 },
      { label: "Midjourney / DALL-E (images)", value: "image_gen", score: 1 },
      { label: "GitHub Copilot (code)", value: "github_copilot", score: 1 },
      { label: "Autres outils IA générative", value: "other", score: 1 },
      { label: "Aucun", value: "none", score: 0 },
    ],
    required: false,
    forPlans: ["starter", "pro", "enterprise"],
    conditions: [{ questionId: "ai_genai_usage", values: ["yes_policy", "yes_free"] }],
    weight: 5,
    collectData: "genAITools",
  },
  {
    id: "ai_hr_recruitment",
    category: "ai_inventory",
    subcategory: "IA RH",
    question: "Utilisez-vous l'IA dans vos processus RH ou de recrutement ?",
    type: "single",
    options: [
      { label: "Non", value: "no", score: 0 },
      { label: "Oui, pour le tri de CV", value: "cv_screening", score: 3, riskLevel: "high" },
      { label: "Oui, pour les entretiens vidéo analysés", value: "video_interview", score: 4, riskLevel: "critical" },
      { label: "Oui, pour l'évaluation des performances", value: "performance", score: 3, riskLevel: "high" },
      { label: "Oui, plusieurs usages RH", value: "multiple", score: 4, riskLevel: "critical" },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 10,
    aiActArticle: "Annexe III - Systèmes à haut risque",
  },
  {
    id: "ai_hr_details",
    category: "ai_inventory",
    subcategory: "IA RH",
    question: "Précisez les outils IA utilisés dans vos processus RH :",
    type: "multiple",
    options: [
      { label: "ATS avec IA (tri automatique de CV)", value: "ats", score: 2 },
      { label: "Analyse vidéo des entretiens", value: "video_analysis", score: 3 },
      { label: "Chatbot recrutement", value: "chatbot", score: 1 },
      { label: "Matching candidat/poste automatisé", value: "matching", score: 2 },
      { label: "Évaluation des soft skills par IA", value: "soft_skills", score: 3 },
      { label: "Prédiction de turnover", value: "turnover", score: 2 },
    ],
    required: false,
    forPlans: ["pro", "enterprise"],
    conditions: [{ questionId: "ai_hr_recruitment", values: ["cv_screening", "video_interview", "performance", "multiple"] }],
    weight: 8,
    collectData: "hrAITools",
  },
  {
    id: "ai_credit_scoring",
    category: "ai_inventory",
    subcategory: "IA Finance",
    question: "Utilisez-vous l'IA pour l'évaluation de solvabilité ou le scoring crédit ?",
    type: "single",
    options: [
      { label: "Non", value: "no", score: 0 },
      { label: "Oui, pour les particuliers", value: "individuals", score: 4, riskLevel: "critical" },
      { label: "Oui, pour les entreprises", value: "businesses", score: 3, riskLevel: "high" },
      { label: "Oui, les deux", value: "both", score: 4, riskLevel: "critical" },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    forSectors: ["finance"],
    weight: 10,
    aiActArticle: "Annexe III - 5(b)",
  },
  {
    id: "ai_biometric",
    category: "ai_inventory",
    subcategory: "Biométrie",
    question: "Utilisez-vous des systèmes de reconnaissance biométrique (faciale, vocale, etc.) ?",
    type: "single",
    options: [
      { label: "Non", value: "no", score: 0 },
      { label: "Oui, pour le contrôle d'accès interne", value: "access_control", score: 2 },
      { label: "Oui, pour l'identification de clients/utilisateurs", value: "client_id", score: 4, riskLevel: "critical" },
      { label: "Oui, pour la surveillance", value: "surveillance", score: 5, riskLevel: "critical" },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 10,
    aiActArticle: "Article 5 - Pratiques interdites",
  },
  {
    id: "ai_customer_service",
    category: "ai_inventory",
    subcategory: "Relation client",
    question: "Utilisez-vous l'IA dans votre relation client ?",
    type: "multiple",
    options: [
      { label: "Chatbot / assistant virtuel", value: "chatbot", score: 1 },
      { label: "Analyse de sentiment des avis", value: "sentiment", score: 1 },
      { label: "Recommandation de produits personnalisée", value: "recommendation", score: 1 },
      { label: "Routage intelligent des demandes", value: "routing", score: 1 },
      { label: "Analyse prédictive du churn", value: "churn", score: 2 },
      { label: "Personnalisation des prix", value: "pricing", score: 3, riskLevel: "high" },
      { label: "Aucun de ces usages", value: "none", score: 0 },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 6,
    collectData: "customerAI",
  },
  {
    id: "ai_marketing",
    category: "ai_inventory",
    subcategory: "Marketing",
    question: "Utilisez-vous l'IA dans vos activités marketing ?",
    type: "multiple",
    options: [
      { label: "Génération de contenu (textes, images)", value: "content_gen", score: 1 },
      { label: "Ciblage publicitaire automatisé", value: "ad_targeting", score: 2 },
      { label: "Scoring et segmentation clients", value: "scoring", score: 2 },
      { label: "A/B testing automatisé", value: "ab_testing", score: 1 },
      { label: "Personnalisation email/web", value: "personalization", score: 1 },
      { label: "Analyse prédictive marketing", value: "predictive", score: 2 },
      { label: "Aucun de ces usages", value: "none", score: 0 },
    ],
    required: true,
    forPlans: ["pro", "enterprise"],
    weight: 5,
    collectData: "marketingAI",
  },
  {
    id: "ai_operations",
    category: "ai_inventory",
    subcategory: "Opérations",
    question: "Utilisez-vous l'IA dans vos opérations ?",
    type: "multiple",
    options: [
      { label: "Prévision de la demande", value: "demand_forecast", score: 1 },
      { label: "Optimisation de la supply chain", value: "supply_chain", score: 1 },
      { label: "Maintenance prédictive", value: "maintenance", score: 1 },
      { label: "Contrôle qualité automatisé", value: "quality", score: 2 },
      { label: "Automatisation de processus (RPA)", value: "rpa", score: 1 },
      { label: "Véhicules/drones autonomes", value: "autonomous", score: 3, riskLevel: "high" },
      { label: "Aucun de ces usages", value: "none", score: 0 },
    ],
    required: true,
    forPlans: ["pro", "enterprise"],
    weight: 5,
    collectData: "operationsAI",
  },
  {
    id: "ai_health_usage",
    category: "ai_inventory",
    subcategory: "IA Santé",
    question: "Utilisez-vous l'IA dans un contexte médical ou de santé ?",
    type: "single",
    options: [
      { label: "Non", value: "no", score: 0 },
      { label: "Oui, aide au diagnostic", value: "diagnosis", score: 4, riskLevel: "critical" },
      { label: "Oui, analyse d'imagerie médicale", value: "imaging", score: 4, riskLevel: "critical" },
      { label: "Oui, suivi patient / objets connectés", value: "monitoring", score: 3, riskLevel: "high" },
      { label: "Oui, autre usage médical", value: "other", score: 3, riskLevel: "high" },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    forSectors: ["health"],
    weight: 10,
    aiActArticle: "Annexe III - 5(a)",
  },
  {
    id: "ai_decision_automation",
    category: "ai_inventory",
    subcategory: "Décisions automatisées",
    question: "Avez-vous des systèmes IA qui prennent des décisions automatisées impactant des personnes ?",
    description: "Décisions sans intervention humaine ayant des effets juridiques ou significatifs.",
    type: "single",
    options: [
      { label: "Non, toutes les décisions sont validées par un humain", value: "no", score: 0 },
      { label: "Oui, pour des décisions mineures", value: "minor", score: 2 },
      { label: "Oui, pour des décisions significatives", value: "significant", score: 4, riskLevel: "high" },
      { label: "Je ne suis pas sûr", value: "unsure", score: 3 },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 9,
    aiActArticle: "Article 14 - Contrôle humain",
  },
  {
    id: "ai_third_party",
    category: "ai_inventory",
    subcategory: "Provenance",
    question: "Vos systèmes IA sont principalement :",
    type: "single",
    options: [
      { label: "Développés en interne", value: "internal", score: 2 },
      { label: "Achetés/loués à des éditeurs", value: "vendor", score: 1 },
      { label: "Open source", value: "opensource", score: 2 },
      { label: "Mix des trois", value: "mixed", score: 2 },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 5,
    collectData: "aiProvenance",
  },
  {
    id: "ai_custom_models",
    category: "ai_inventory",
    subcategory: "Développement",
    question: "Développez-vous ou entraînez-vous vos propres modèles d'IA ?",
    type: "single",
    options: [
      { label: "Non, nous utilisons uniquement des solutions clé en main", value: "no", score: 0 },
      { label: "Oui, nous fine-tunons des modèles existants", value: "finetune", score: 2 },
      { label: "Oui, nous développons des modèles from scratch", value: "custom", score: 3 },
    ],
    required: true,
    forPlans: ["pro", "enterprise"],
    weight: 6,
    aiActArticle: "Article 16 - Obligations fournisseurs",
  },

  // ============================================
  // CLASSIFICATION DES RISQUES (20 questions)
  // ============================================
  {
    id: "risk_classification_done",
    category: "risk_classification",
    subcategory: "Analyse",
    question: "Avez-vous classifié vos systèmes IA selon les 4 niveaux de risque de l'AI Act ?",
    description: "Inacceptable, Haut risque, Risque limité, Risque minimal",
    type: "single",
    options: [
      { label: "Oui, classification complète", value: "complete", score: 0 },
      { label: "En cours de réalisation", value: "in_progress", score: 2 },
      { label: "Non, pas encore fait", value: "no", score: 4 },
      { label: "Je ne connais pas cette classification", value: "unknown", score: 5 },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 10,
    aiActArticle: "Article 6 - Classification",
  },
  {
    id: "risk_prohibited_check",
    category: "risk_classification",
    subcategory: "Pratiques interdites",
    question: "Avez-vous vérifié qu'aucun de vos systèmes n'utilise de pratiques interdites ?",
    description: "Manipulation subliminale, exploitation de vulnérabilités, scoring social, reconnaissance faciale en temps réel dans l'espace public...",
    type: "single",
    options: [
      { label: "Oui, vérification formelle réalisée", value: "verified", score: 0 },
      { label: "Oui, vérification informelle", value: "informal", score: 2 },
      { label: "Non, pas vérifié", value: "no", score: 4 },
      { label: "Je ne connais pas les pratiques interdites", value: "unknown", score: 5 },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 10,
    aiActArticle: "Article 5 - Pratiques interdites",
  },
  {
    id: "risk_social_scoring",
    category: "risk_classification",
    subcategory: "Pratiques interdites",
    question: "Utilisez-vous un système de notation sociale des personnes basé sur leur comportement ?",
    type: "single",
    options: [
      { label: "Non, absolument pas", value: "no", score: 0 },
      { label: "Nous avons un système de fidélité/points", value: "loyalty", score: 1 },
      { label: "Nous notons les comportements pour prendre des décisions", value: "yes", score: 5, riskLevel: "critical" },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 10,
    aiActArticle: "Article 5(1)(c)",
  },
  {
    id: "risk_emotion_recognition",
    category: "risk_classification",
    subcategory: "Pratiques interdites",
    question: "Utilisez-vous la reconnaissance des émotions ?",
    type: "single",
    options: [
      { label: "Non", value: "no", score: 0 },
      { label: "Oui, en contexte professionnel (RH, entretiens)", value: "workplace", score: 5, riskLevel: "critical" },
      { label: "Oui, en contexte éducatif", value: "education", score: 5, riskLevel: "critical" },
      { label: "Oui, pour l'analyse marketing", value: "marketing", score: 3, riskLevel: "high" },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 10,
    aiActArticle: "Article 5(1)(f)",
  },
  {
    id: "risk_high_risk_count",
    category: "risk_classification",
    subcategory: "Haut risque",
    question: "Combien de systèmes à haut risque avez-vous identifiés ?",
    type: "single",
    options: [
      { label: "Aucun", value: "0", score: 0 },
      { label: "1-2 systèmes", value: "1_2", score: 2 },
      { label: "3-5 systèmes", value: "3_5", score: 3 },
      { label: "Plus de 5 systèmes", value: "5_plus", score: 4 },
      { label: "Je ne sais pas", value: "unknown", score: 4 },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 8,
    collectData: "highRiskCount",
  },
  {
    id: "risk_critical_infrastructure",
    category: "risk_classification",
    subcategory: "Haut risque",
    question: "Vos systèmes IA interagissent-ils avec des infrastructures critiques ?",
    description: "Énergie, eau, transports, télécommunications, santé...",
    type: "single",
    options: [
      { label: "Non", value: "no", score: 0 },
      { label: "Oui, de manière périphérique", value: "peripheral", score: 2 },
      { label: "Oui, de manière centrale", value: "central", score: 4, riskLevel: "high" },
    ],
    required: true,
    forPlans: ["pro", "enterprise"],
    weight: 8,
    aiActArticle: "Annexe III - 2",
  },
  {
    id: "risk_education_ai",
    category: "risk_classification",
    subcategory: "Haut risque",
    question: "Utilisez-vous l'IA dans l'éducation ou la formation professionnelle ?",
    type: "single",
    options: [
      { label: "Non", value: "no", score: 0 },
      { label: "Oui, pour l'administration (planning, etc.)", value: "admin", score: 1 },
      { label: "Oui, pour l'évaluation des apprenants", value: "assessment", score: 4, riskLevel: "high" },
      { label: "Oui, pour l'orientation/admission", value: "admission", score: 4, riskLevel: "high" },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    forSectors: ["education"],
    weight: 8,
    aiActArticle: "Annexe III - 3",
  },
  {
    id: "risk_law_enforcement",
    category: "risk_classification",
    subcategory: "Haut risque",
    question: "Fournissez-vous des systèmes IA aux forces de l'ordre ou à la justice ?",
    type: "single",
    options: [
      { label: "Non", value: "no", score: 0 },
      { label: "Oui", value: "yes", score: 5, riskLevel: "critical" },
    ],
    required: true,
    forPlans: ["pro", "enterprise"],
    weight: 10,
    aiActArticle: "Annexe III - 6, 7, 8",
  },
  {
    id: "risk_fundamental_rights",
    category: "risk_classification",
    subcategory: "Impact",
    question: "Vos systèmes IA peuvent-ils impacter les droits fondamentaux des personnes ?",
    description: "Droit au travail, à la santé, à l'éducation, non-discrimination...",
    type: "single",
    options: [
      { label: "Non, impact minimal", value: "minimal", score: 0 },
      { label: "Impact possible mais limité", value: "limited", score: 2 },
      { label: "Impact significatif possible", value: "significant", score: 4, riskLevel: "high" },
      { label: "Je ne sais pas évaluer", value: "unknown", score: 3 },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 9,
    aiActArticle: "Article 27 - FRIA",
  },
  {
    id: "risk_fria_done",
    category: "risk_classification",
    subcategory: "Impact",
    question: "Avez-vous réalisé une analyse d'impact sur les droits fondamentaux (FRIA) ?",
    type: "single",
    options: [
      { label: "Oui, pour tous les systèmes à haut risque", value: "complete", score: 0 },
      { label: "Oui, pour certains systèmes", value: "partial", score: 2 },
      { label: "Non, mais prévu", value: "planned", score: 3 },
      { label: "Non", value: "no", score: 4 },
      { label: "Je ne connais pas le FRIA", value: "unknown", score: 4 },
    ],
    required: true,
    forPlans: ["pro", "enterprise"],
    weight: 8,
    aiActArticle: "Article 27",
  },

  // ============================================
  // GOUVERNANCE (20 questions)
  // ============================================
  {
    id: "gov_ai_referent",
    category: "governance",
    subcategory: "Organisation",
    question: "Avez-vous désigné un référent IA ou responsable de la conformité AI Act ?",
    type: "single",
    options: [
      { label: "Oui, poste dédié à temps plein", value: "fulltime", score: 0 },
      { label: "Oui, responsabilité partagée avec d'autres fonctions", value: "shared", score: 1 },
      { label: "Non, mais prévu", value: "planned", score: 2 },
      { label: "Non", value: "no", score: 4 },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 8,
    collectData: "hasAIReferent",
  },
  {
    id: "gov_ai_referent_level",
    category: "governance",
    subcategory: "Organisation",
    question: "À quel niveau hiérarchique est rattaché le référent IA ?",
    type: "single",
    options: [
      { label: "Direction générale / COMEX", value: "executive", score: 0 },
      { label: "Direction (DSI, DRH, Juridique...)", value: "director", score: 1 },
      { label: "Management intermédiaire", value: "middle", score: 2 },
      { label: "Pas de référent désigné", value: "none", score: 3 },
    ],
    required: true,
    forPlans: ["pro", "enterprise"],
    conditions: [{ questionId: "gov_ai_referent", values: ["fulltime", "shared"] }],
    weight: 5,
  },
  {
    id: "gov_ai_committee",
    category: "governance",
    subcategory: "Organisation",
    question: "Existe-t-il un comité ou une instance de gouvernance IA ?",
    type: "single",
    options: [
      { label: "Oui, comité dédié avec réunions régulières", value: "dedicated", score: 0 },
      { label: "Oui, traité dans un comité existant (comité data, risques...)", value: "existing", score: 1 },
      { label: "Non, mais prévu", value: "planned", score: 2 },
      { label: "Non", value: "no", score: 3 },
    ],
    required: true,
    forPlans: ["pro", "enterprise"],
    weight: 6,
  },
  {
    id: "gov_ai_policy",
    category: "governance",
    subcategory: "Politique",
    question: "Avez-vous une politique d'utilisation de l'IA formalisée ?",
    type: "single",
    options: [
      { label: "Oui, validée et diffusée à tous", value: "complete", score: 0 },
      { label: "Oui, mais pas encore diffusée", value: "draft", score: 1 },
      { label: "En cours de rédaction", value: "in_progress", score: 2 },
      { label: "Non", value: "no", score: 4 },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 8,
    collectData: "hasAIPolicy",
  },
  {
    id: "gov_policy_content",
    category: "governance",
    subcategory: "Politique",
    question: "Que couvre votre politique IA ?",
    type: "multiple",
    options: [
      { label: "Usages autorisés / interdits", value: "usage_rules", score: 0 },
      { label: "Processus de validation des nouveaux outils", value: "validation", score: 0 },
      { label: "Confidentialité et données", value: "confidentiality", score: 0 },
      { label: "Rôles et responsabilités", value: "roles", score: 0 },
      { label: "Gestion des incidents", value: "incidents", score: 0 },
      { label: "Formation obligatoire", value: "training", score: 0 },
    ],
    required: false,
    forPlans: ["pro", "enterprise"],
    conditions: [{ questionId: "gov_ai_policy", values: ["complete", "draft"] }],
    weight: 5,
    collectData: "policyContent",
  },
  {
    id: "gov_new_tool_process",
    category: "governance",
    subcategory: "Processus",
    question: "Existe-t-il un processus formel pour l'adoption de nouveaux outils IA ?",
    type: "single",
    options: [
      { label: "Oui, processus documenté avec validation multi-niveaux", value: "formal", score: 0 },
      { label: "Oui, processus informel", value: "informal", score: 2 },
      { label: "Non, adoption libre par les équipes", value: "free", score: 4 },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 7,
  },
  {
    id: "gov_shadow_ai",
    category: "governance",
    subcategory: "Processus",
    question: "Maîtrisez-vous le 'Shadow AI' (usage non autorisé d'IA par les collaborateurs) ?",
    type: "single",
    options: [
      { label: "Oui, surveillance et blocage des outils non autorisés", value: "controlled", score: 0 },
      { label: "Oui, sensibilisation mais pas de blocage technique", value: "awareness", score: 2 },
      { label: "Non, nous n'avons pas de visibilité", value: "no_visibility", score: 4 },
    ],
    required: true,
    forPlans: ["pro", "enterprise"],
    weight: 7,
  },
  {
    id: "gov_board_involvement",
    category: "governance",
    subcategory: "Direction",
    question: "La direction générale est-elle impliquée dans la stratégie IA ?",
    type: "single",
    options: [
      { label: "Oui, sujet régulier en COMEX/CODIR", value: "regular", score: 0 },
      { label: "Oui, ponctuellement", value: "occasional", score: 1 },
      { label: "Non, délégué aux équipes opérationnelles", value: "delegated", score: 2 },
      { label: "Non, pas de stratégie IA définie", value: "no_strategy", score: 3 },
    ],
    required: true,
    forPlans: ["pro", "enterprise"],
    weight: 5,
  },
  {
    id: "gov_budget_compliance",
    category: "governance",
    subcategory: "Budget",
    question: "Avez-vous alloué un budget spécifique pour la conformité AI Act ?",
    type: "single",
    options: [
      { label: "Oui, budget dédié", value: "dedicated", score: 0 },
      { label: "Oui, inclus dans le budget IT/juridique", value: "included", score: 1 },
      { label: "Non, pas de budget prévu", value: "no", score: 3 },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 6,
    collectData: "complianceBudget",
  },
  {
    id: "gov_kpis",
    category: "governance",
    subcategory: "Suivi",
    question: "Avez-vous défini des indicateurs (KPIs) pour suivre l'utilisation et la performance de vos IA ?",
    type: "single",
    options: [
      { label: "Oui, tableau de bord avec suivi régulier", value: "dashboard", score: 0 },
      { label: "Oui, quelques indicateurs suivis ponctuellement", value: "partial", score: 2 },
      { label: "Non", value: "no", score: 3 },
    ],
    required: true,
    forPlans: ["pro", "enterprise"],
    weight: 5,
  },

  // ============================================
  // DOCUMENTATION (15 questions)
  // ============================================
  {
    id: "doc_technical_exists",
    category: "documentation",
    subcategory: "Documentation technique",
    question: "Disposez-vous d'une documentation technique pour vos systèmes IA à haut risque ?",
    type: "single",
    options: [
      { label: "Oui, documentation complète et à jour", value: "complete", score: 0 },
      { label: "Oui, documentation partielle", value: "partial", score: 2 },
      { label: "Non, mais nous avons la documentation fournisseur", value: "vendor_only", score: 3 },
      { label: "Non", value: "no", score: 4 },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 8,
    aiActArticle: "Article 11 - Documentation technique",
  },
  {
    id: "doc_content",
    category: "documentation",
    subcategory: "Documentation technique",
    question: "Votre documentation technique inclut-elle :",
    type: "multiple",
    options: [
      { label: "Description générale du système", value: "description", score: 0 },
      { label: "Spécifications de conception", value: "design_specs", score: 0 },
      { label: "Description des données d'entraînement", value: "training_data", score: 0 },
      { label: "Métriques de performance", value: "metrics", score: 0 },
      { label: "Instructions d'utilisation", value: "instructions", score: 0 },
      { label: "Mesures de gestion des risques", value: "risk_measures", score: 0 },
    ],
    required: false,
    forPlans: ["pro", "enterprise"],
    weight: 6,
  },
  {
    id: "doc_logs",
    category: "documentation",
    subcategory: "Traçabilité",
    question: "Conservez-vous les logs de fonctionnement de vos systèmes IA ?",
    type: "single",
    options: [
      { label: "Oui, conservation conforme (minimum 6 mois)", value: "compliant", score: 0 },
      { label: "Oui, mais durée insuffisante", value: "short_term", score: 2 },
      { label: "Partiellement (certains systèmes)", value: "partial", score: 3 },
      { label: "Non", value: "no", score: 4 },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 8,
    aiActArticle: "Article 12 - Tenue de registres",
  },
  {
    id: "doc_logs_content",
    category: "documentation",
    subcategory: "Traçabilité",
    question: "Que contiennent vos logs ?",
    type: "multiple",
    options: [
      { label: "Horodatage des opérations", value: "timestamp", score: 0 },
      { label: "Données d'entrée", value: "input", score: 0 },
      { label: "Résultats/décisions", value: "output", score: 0 },
      { label: "Identifiant utilisateur", value: "user_id", score: 0 },
      { label: "Versions du modèle", value: "model_version", score: 0 },
    ],
    required: false,
    forPlans: ["pro", "enterprise"],
    conditions: [{ questionId: "doc_logs", values: ["compliant", "short_term", "partial"] }],
    weight: 5,
  },
  {
    id: "doc_training_data",
    category: "documentation",
    subcategory: "Données",
    question: "Avez-vous documenté les données utilisées pour entraîner vos modèles IA ?",
    type: "single",
    options: [
      { label: "Oui, documentation complète (source, qualité, biais)", value: "complete", score: 0 },
      { label: "Oui, documentation basique", value: "basic", score: 2 },
      { label: "Non applicable (modèles pré-entraînés)", value: "not_applicable", score: 1 },
      { label: "Non", value: "no", score: 4 },
    ],
    required: true,
    forPlans: ["pro", "enterprise"],
    weight: 7,
    aiActArticle: "Article 10 - Données",
  },
  {
    id: "doc_bias_analysis",
    category: "documentation",
    subcategory: "Données",
    question: "Avez-vous analysé et documenté les biais potentiels de vos systèmes IA ?",
    type: "single",
    options: [
      { label: "Oui, analyse formelle avec mesures correctives", value: "formal", score: 0 },
      { label: "Oui, analyse informelle", value: "informal", score: 2 },
      { label: "Non, mais prévu", value: "planned", score: 3 },
      { label: "Non", value: "no", score: 4 },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 8,
    aiActArticle: "Article 10(2)(f)",
  },
  {
    id: "doc_version_control",
    category: "documentation",
    subcategory: "Gestion",
    question: "Avez-vous un système de gestion des versions pour vos modèles IA ?",
    type: "single",
    options: [
      { label: "Oui, versionning formel avec historique", value: "formal", score: 0 },
      { label: "Oui, basique", value: "basic", score: 1 },
      { label: "Non", value: "no", score: 3 },
    ],
    required: true,
    forPlans: ["pro", "enterprise"],
    weight: 5,
  },
  {
    id: "doc_update_process",
    category: "documentation",
    subcategory: "Gestion",
    question: "Avez-vous un processus de mise à jour de la documentation ?",
    type: "single",
    options: [
      { label: "Oui, mise à jour systématique à chaque changement", value: "systematic", score: 0 },
      { label: "Oui, mises à jour périodiques", value: "periodic", score: 1 },
      { label: "Non, mises à jour ad hoc", value: "adhoc", score: 3 },
    ],
    required: true,
    forPlans: ["pro", "enterprise"],
    weight: 4,
  },

  // ============================================
  // FORMATION (15 questions)
  // ============================================
  {
    id: "training_ai_act_awareness",
    category: "training",
    subcategory: "Sensibilisation",
    question: "Vos collaborateurs sont-ils sensibilisés à l'AI Act ?",
    type: "single",
    options: [
      { label: "Oui, formation dédiée réalisée", value: "trained", score: 0 },
      { label: "Oui, sensibilisation basique", value: "awareness", score: 1 },
      { label: "Non, pas encore", value: "no", score: 3 },
      { label: "L'AI Act n'est pas connu en interne", value: "unknown", score: 4 },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 8,
    aiActArticle: "Article 4 - Maîtrise de l'IA",
  },
  {
    id: "training_article4_compliance",
    category: "training",
    subcategory: "Obligation légale",
    question: "Êtes-vous conforme à l'Article 4 de l'AI Act (obligation de formation) ?",
    description: "L'Article 4 impose que les personnes utilisant des systèmes IA aient un niveau suffisant de maîtrise.",
    type: "single",
    options: [
      { label: "Oui, plan de formation déployé", value: "compliant", score: 0 },
      { label: "En cours de mise en conformité", value: "in_progress", score: 2 },
      { label: "Non, pas encore commencé", value: "no", score: 3 },
      { label: "Je ne connaissais pas cette obligation", value: "unknown", score: 4 },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 9,
    aiActArticle: "Article 4",
  },
  {
    id: "training_plan_exists",
    category: "training",
    subcategory: "Plan de formation",
    question: "Avez-vous un plan de formation IA formalisé ?",
    type: "single",
    options: [
      { label: "Oui, plan annuel avec budget", value: "formal", score: 0 },
      { label: "Oui, formations ponctuelles", value: "occasional", score: 2 },
      { label: "Non", value: "no", score: 3 },
    ],
    required: true,
    forPlans: ["pro", "enterprise"],
    weight: 6,
    collectData: "hasTrainingPlan",
  },
  {
    id: "training_target_audiences",
    category: "training",
    subcategory: "Plan de formation",
    question: "Quelles populations sont formées à l'IA ?",
    type: "multiple",
    options: [
      { label: "Direction / COMEX", value: "executive", score: 0 },
      { label: "Managers", value: "managers", score: 0 },
      { label: "Équipes IT / Data", value: "tech", score: 0 },
      { label: "Utilisateurs métiers", value: "business", score: 0 },
      { label: "Équipes juridiques / conformité", value: "legal", score: 0 },
      { label: "Nouveaux arrivants (onboarding)", value: "onboarding", score: 0 },
    ],
    required: false,
    forPlans: ["pro", "enterprise"],
    weight: 5,
    collectData: "trainedAudiences",
  },
  {
    id: "training_certification",
    category: "training",
    subcategory: "Certification",
    question: "Des collaborateurs ont-ils une certification IA ou AI Act ?",
    type: "single",
    options: [
      { label: "Oui, plusieurs personnes certifiées", value: "multiple", score: 0 },
      { label: "Oui, quelques personnes", value: "few", score: 1 },
      { label: "Non, mais prévu", value: "planned", score: 2 },
      { label: "Non", value: "no", score: 3 },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 5,
  },
  {
    id: "training_high_risk_operators",
    category: "training",
    subcategory: "Opérateurs",
    question: "Les opérateurs de vos systèmes à haut risque sont-ils spécifiquement formés ?",
    type: "single",
    options: [
      { label: "Oui, formation spécifique obligatoire", value: "mandatory", score: 0 },
      { label: "Oui, formation recommandée", value: "recommended", score: 1 },
      { label: "Non", value: "no", score: 3 },
      { label: "Pas de système à haut risque", value: "not_applicable", score: 0 },
    ],
    required: true,
    forPlans: ["pro", "enterprise"],
    weight: 7,
    aiActArticle: "Article 26(7)",
  },
  {
    id: "training_refresh",
    category: "training",
    subcategory: "Mise à jour",
    question: "Les formations IA sont-elles mises à jour régulièrement ?",
    type: "single",
    options: [
      { label: "Oui, mise à jour annuelle ou plus fréquente", value: "annual", score: 0 },
      { label: "Oui, ponctuellement", value: "occasional", score: 1 },
      { label: "Non, formations figées", value: "no", score: 3 },
    ],
    required: true,
    forPlans: ["pro", "enterprise"],
    weight: 4,
  },

  // ============================================
  // GESTION DES DONNÉES (12 questions)
  // ============================================
  {
    id: "data_quality_process",
    category: "data_management",
    subcategory: "Qualité",
    question: "Avez-vous un processus de contrôle qualité des données utilisées par vos IA ?",
    type: "single",
    options: [
      { label: "Oui, processus formalisé", value: "formal", score: 0 },
      { label: "Oui, contrôles ponctuels", value: "occasional", score: 2 },
      { label: "Non", value: "no", score: 4 },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 7,
    aiActArticle: "Article 10",
  },
  {
    id: "data_representativeness",
    category: "data_management",
    subcategory: "Qualité",
    question: "Vérifiez-vous la représentativité des données d'entraînement ?",
    type: "single",
    options: [
      { label: "Oui, analyse systématique", value: "systematic", score: 0 },
      { label: "Oui, pour certains systèmes", value: "partial", score: 2 },
      { label: "Non", value: "no", score: 3 },
    ],
    required: true,
    forPlans: ["pro", "enterprise"],
    weight: 6,
    aiActArticle: "Article 10(3)",
  },
  {
    id: "data_gdpr_compliance",
    category: "data_management",
    subcategory: "RGPD",
    question: "Vos traitements IA sont-ils conformes au RGPD ?",
    type: "single",
    options: [
      { label: "Oui, conformité vérifiée et documentée", value: "verified", score: 0 },
      { label: "Oui, nous pensons être conformes", value: "assumed", score: 1 },
      { label: "Partiellement", value: "partial", score: 3 },
      { label: "Non / Je ne sais pas", value: "no", score: 4 },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 8,
  },
  {
    id: "data_pia",
    category: "data_management",
    subcategory: "RGPD",
    question: "Avez-vous réalisé des analyses d'impact (PIA/AIPD) pour vos systèmes IA ?",
    type: "single",
    options: [
      { label: "Oui, pour tous les systèmes concernés", value: "all", score: 0 },
      { label: "Oui, pour certains systèmes", value: "some", score: 2 },
      { label: "Non", value: "no", score: 3 },
    ],
    required: true,
    forPlans: ["pro", "enterprise"],
    weight: 7,
  },
  {
    id: "data_retention",
    category: "data_management",
    subcategory: "Conservation",
    question: "Avez-vous défini des durées de conservation pour les données IA ?",
    type: "single",
    options: [
      { label: "Oui, politique de rétention formalisée", value: "formal", score: 0 },
      { label: "Oui, durées définies au cas par cas", value: "adhoc", score: 1 },
      { label: "Non", value: "no", score: 3 },
    ],
    required: true,
    forPlans: ["pro", "enterprise"],
    weight: 5,
  },
  {
    id: "data_lineage",
    category: "data_management",
    subcategory: "Traçabilité",
    question: "Êtes-vous capable de tracer l'origine des données utilisées par vos IA ?",
    type: "single",
    options: [
      { label: "Oui, data lineage complet", value: "complete", score: 0 },
      { label: "Oui, partiellement", value: "partial", score: 2 },
      { label: "Non", value: "no", score: 3 },
    ],
    required: true,
    forPlans: ["enterprise"],
    weight: 6,
    aiActArticle: "Article 10(2)",
  },

  // ============================================
  // TRANSPARENCE (10 questions)
  // ============================================
  {
    id: "transparency_disclosure",
    category: "transparency",
    subcategory: "Information",
    question: "Informez-vous les utilisateurs qu'ils interagissent avec un système IA ?",
    type: "single",
    options: [
      { label: "Oui, systématiquement et clairement", value: "always", score: 0 },
      { label: "Oui, dans certains cas", value: "sometimes", score: 2 },
      { label: "Non", value: "no", score: 4 },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 8,
    aiActArticle: "Article 50 - Transparence",
  },
  {
    id: "transparency_chatbot",
    category: "transparency",
    subcategory: "Information",
    question: "Vos chatbots ou assistants virtuels s'identifient-ils comme étant des IA ?",
    type: "single",
    options: [
      { label: "Oui, identification claire", value: "clear", score: 0 },
      { label: "Partiellement", value: "partial", score: 2 },
      { label: "Non", value: "no", score: 4 },
      { label: "Pas de chatbot", value: "not_applicable", score: 0 },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 7,
    aiActArticle: "Article 50(1)",
  },
  {
    id: "transparency_synthetic_content",
    category: "transparency",
    subcategory: "Contenu généré",
    question: "Marquez-vous le contenu généré par IA (textes, images, vidéos) ?",
    type: "single",
    options: [
      { label: "Oui, marquage systématique", value: "always", score: 0 },
      { label: "Oui, parfois", value: "sometimes", score: 2 },
      { label: "Non", value: "no", score: 3 },
      { label: "Pas de contenu généré par IA", value: "not_applicable", score: 0 },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 6,
    aiActArticle: "Article 50(2)",
  },
  {
    id: "transparency_decisions",
    category: "transparency",
    subcategory: "Décisions",
    question: "Expliquez-vous les décisions prises par vos systèmes IA aux personnes concernées ?",
    type: "single",
    options: [
      { label: "Oui, explications systématiques", value: "always", score: 0 },
      { label: "Oui, sur demande", value: "on_request", score: 1 },
      { label: "Non", value: "no", score: 3 },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 7,
  },
  {
    id: "transparency_privacy_policy",
    category: "transparency",
    subcategory: "Documentation",
    question: "Votre politique de confidentialité mentionne-t-elle l'utilisation de l'IA ?",
    type: "single",
    options: [
      { label: "Oui, section dédiée", value: "dedicated", score: 0 },
      { label: "Oui, mention générale", value: "general", score: 1 },
      { label: "Non", value: "no", score: 3 },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 5,
  },
  {
    id: "transparency_cgv",
    category: "transparency",
    subcategory: "Documentation",
    question: "Vos CGU/CGV mentionnent-elles l'utilisation de systèmes IA ?",
    type: "single",
    options: [
      { label: "Oui, clauses spécifiques IA", value: "specific", score: 0 },
      { label: "Non", value: "no", score: 2 },
      { label: "Pas de CGU/CGV", value: "not_applicable", score: 1 },
    ],
    required: true,
    forPlans: ["pro", "enterprise"],
    weight: 4,
  },

  // ============================================
  // SUPERVISION HUMAINE (10 questions)
  // ============================================
  {
    id: "human_oversight_policy",
    category: "human_oversight",
    subcategory: "Politique",
    question: "Avez-vous défini une politique de supervision humaine pour vos systèmes IA ?",
    type: "single",
    options: [
      { label: "Oui, politique formalisée", value: "formal", score: 0 },
      { label: "Oui, règles informelles", value: "informal", score: 2 },
      { label: "Non", value: "no", score: 4 },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 8,
    aiActArticle: "Article 14 - Contrôle humain",
  },
  {
    id: "human_oversight_high_risk",
    category: "human_oversight",
    subcategory: "Haut risque",
    question: "Vos systèmes à haut risque permettent-ils une intervention humaine ?",
    type: "single",
    options: [
      { label: "Oui, intervention possible à tout moment", value: "always", score: 0 },
      { label: "Oui, mais limitée", value: "limited", score: 2 },
      { label: "Non", value: "no", score: 4 },
      { label: "Pas de système à haut risque", value: "not_applicable", score: 0 },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 9,
    aiActArticle: "Article 14(2)",
  },
  {
    id: "human_override",
    category: "human_oversight",
    subcategory: "Capacité",
    question: "Les opérateurs peuvent-ils annuler ou corriger les décisions IA ?",
    type: "single",
    options: [
      { label: "Oui, facilement", value: "easy", score: 0 },
      { label: "Oui, mais processus complexe", value: "complex", score: 2 },
      { label: "Non", value: "no", score: 4 },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 8,
    aiActArticle: "Article 14(4)(d)",
  },
  {
    id: "human_stop_button",
    category: "human_oversight",
    subcategory: "Capacité",
    question: "Existe-t-il un mécanisme d'arrêt d'urgence pour vos systèmes IA critiques ?",
    type: "single",
    options: [
      { label: "Oui, bouton d'arrêt accessible", value: "accessible", score: 0 },
      { label: "Oui, mais procédure complexe", value: "complex", score: 2 },
      { label: "Non", value: "no", score: 4 },
      { label: "Pas de système critique", value: "not_applicable", score: 0 },
    ],
    required: true,
    forPlans: ["pro", "enterprise"],
    weight: 7,
    aiActArticle: "Article 14(4)(e)",
  },
  {
    id: "human_automation_bias",
    category: "human_oversight",
    subcategory: "Formation",
    question: "Vos équipes sont-elles formées au risque de biais d'automatisation ?",
    description: "Tendance à faire confiance aveuglément aux décisions de l'IA.",
    type: "single",
    options: [
      { label: "Oui, formation spécifique", value: "trained", score: 0 },
      { label: "Oui, sensibilisation basique", value: "awareness", score: 1 },
      { label: "Non", value: "no", score: 3 },
    ],
    required: true,
    forPlans: ["pro", "enterprise"],
    weight: 6,
    aiActArticle: "Article 14(4)(b)",
  },

  // ============================================
  // SÉCURITÉ (10 questions)
  // ============================================
  {
    id: "security_risk_assessment",
    category: "security",
    subcategory: "Évaluation",
    question: "Avez-vous réalisé une évaluation des risques de sécurité de vos systèmes IA ?",
    type: "single",
    options: [
      { label: "Oui, évaluation formelle", value: "formal", score: 0 },
      { label: "Oui, évaluation informelle", value: "informal", score: 2 },
      { label: "Non", value: "no", score: 4 },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 8,
    aiActArticle: "Article 9 - Gestion des risques",
  },
  {
    id: "security_adversarial",
    category: "security",
    subcategory: "Robustesse",
    question: "Avez-vous testé la robustesse de vos IA face aux attaques adversariales ?",
    description: "Tentatives de manipulation des entrées pour tromper le modèle.",
    type: "single",
    options: [
      { label: "Oui, tests réguliers", value: "regular", score: 0 },
      { label: "Oui, tests ponctuels", value: "occasional", score: 2 },
      { label: "Non", value: "no", score: 3 },
    ],
    required: true,
    forPlans: ["pro", "enterprise"],
    weight: 6,
    aiActArticle: "Article 15(4)",
  },
  {
    id: "security_data_poisoning",
    category: "security",
    subcategory: "Robustesse",
    question: "Avez-vous des mesures contre l'empoisonnement des données ?",
    type: "single",
    options: [
      { label: "Oui, mesures en place", value: "yes", score: 0 },
      { label: "Partiellement", value: "partial", score: 2 },
      { label: "Non", value: "no", score: 3 },
    ],
    required: true,
    forPlans: ["enterprise"],
    weight: 5,
    aiActArticle: "Article 15(4)",
  },
  {
    id: "security_access_control",
    category: "security",
    subcategory: "Accès",
    question: "Les accès à vos systèmes IA sont-ils contrôlés et tracés ?",
    type: "single",
    options: [
      { label: "Oui, contrôle strict avec logs", value: "strict", score: 0 },
      { label: "Oui, contrôle basique", value: "basic", score: 1 },
      { label: "Non", value: "no", score: 3 },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 6,
  },
  {
    id: "security_incident_process",
    category: "security",
    subcategory: "Incidents",
    question: "Avez-vous un processus de gestion des incidents IA ?",
    type: "single",
    options: [
      { label: "Oui, processus formalisé", value: "formal", score: 0 },
      { label: "Oui, géré au cas par cas", value: "adhoc", score: 2 },
      { label: "Non", value: "no", score: 3 },
    ],
    required: true,
    forPlans: ["pro", "enterprise"],
    weight: 7,
    aiActArticle: "Article 72 - Signalement",
  },
  {
    id: "security_incident_reporting",
    category: "security",
    subcategory: "Incidents",
    question: "Savez-vous à qui signaler un incident grave lié à l'IA ?",
    type: "single",
    options: [
      { label: "Oui, autorités identifiées et processus clair", value: "clear", score: 0 },
      { label: "Oui, mais processus flou", value: "unclear", score: 2 },
      { label: "Non", value: "no", score: 3 },
    ],
    required: true,
    forPlans: ["pro", "enterprise"],
    weight: 5,
    aiActArticle: "Article 73",
  },

  // ============================================
  // PROCESSUS DE CONFORMITÉ (10 questions)
  // ============================================
  {
    id: "compliance_roadmap",
    category: "compliance_process",
    subcategory: "Planification",
    question: "Avez-vous établi une roadmap de mise en conformité AI Act ?",
    type: "single",
    options: [
      { label: "Oui, roadmap détaillée avec jalons", value: "detailed", score: 0 },
      { label: "Oui, plan global", value: "global", score: 1 },
      { label: "Non, mais prévu", value: "planned", score: 2 },
      { label: "Non", value: "no", score: 4 },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 8,
    collectData: "hasRoadmap",
  },
  {
    id: "compliance_deadline_awareness",
    category: "compliance_process",
    subcategory: "Planification",
    question: "Connaissez-vous les échéances de l'AI Act ?",
    description: "Février 2025 (pratiques interdites), Août 2025 (GPAI), Août 2026 (haut risque)...",
    type: "single",
    options: [
      { label: "Oui, échéances intégrées dans notre planning", value: "integrated", score: 0 },
      { label: "Oui, connaissance générale", value: "general", score: 1 },
      { label: "Non, je découvre", value: "no", score: 3 },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 7,
  },
  {
    id: "compliance_external_help",
    category: "compliance_process",
    subcategory: "Ressources",
    question: "Faites-vous appel à une aide externe pour la conformité AI Act ?",
    type: "single",
    options: [
      { label: "Oui, cabinet spécialisé IA/tech", value: "specialized", score: 0 },
      { label: "Oui, cabinet juridique généraliste", value: "legal", score: 1 },
      { label: "Non, tout en interne", value: "internal", score: 2 },
      { label: "Non, pas encore commencé", value: "no", score: 3 },
    ],
    required: true,
    forPlans: ["pro", "enterprise"],
    weight: 4,
  },
  {
    id: "compliance_register",
    category: "compliance_process",
    subcategory: "Documentation",
    question: "Tenez-vous un registre des systèmes IA conforme à l'AI Act ?",
    type: "single",
    options: [
      { label: "Oui, registre complet", value: "complete", score: 0 },
      { label: "Oui, registre partiel", value: "partial", score: 2 },
      { label: "Non", value: "no", score: 4 },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 8,
    aiActArticle: "Article 49 - Registre",
    collectData: "hasRegister",
  },
  {
    id: "compliance_eu_database",
    category: "compliance_process",
    subcategory: "Enregistrement",
    question: "Avez-vous prévu d'enregistrer vos systèmes à haut risque dans la base UE ?",
    type: "single",
    options: [
      { label: "Oui, processus en place", value: "yes", score: 0 },
      { label: "Oui, prévu", value: "planned", score: 1 },
      { label: "Non, je ne connaissais pas cette obligation", value: "unknown", score: 3 },
      { label: "Non applicable (pas de système à haut risque)", value: "not_applicable", score: 0 },
    ],
    required: true,
    forPlans: ["pro", "enterprise"],
    weight: 6,
    aiActArticle: "Article 71",
  },
  {
    id: "compliance_internal_audit",
    category: "compliance_process",
    subcategory: "Contrôle",
    question: "Réalisez-vous des audits internes de conformité IA ?",
    type: "single",
    options: [
      { label: "Oui, audits réguliers programmés", value: "regular", score: 0 },
      { label: "Oui, ponctuellement", value: "occasional", score: 2 },
      { label: "Non", value: "no", score: 3 },
    ],
    required: true,
    forPlans: ["pro", "enterprise"],
    weight: 5,
  },
  {
    id: "compliance_ce_marking",
    category: "compliance_process",
    subcategory: "Certification",
    question: "Connaissez-vous les exigences de marquage CE pour les systèmes IA à haut risque ?",
    type: "single",
    options: [
      { label: "Oui, processus de certification en place", value: "process", score: 0 },
      { label: "Oui, connaissance théorique", value: "theory", score: 1 },
      { label: "Non", value: "no", score: 2 },
      { label: "Non applicable", value: "not_applicable", score: 0 },
    ],
    required: true,
    forPlans: ["pro", "enterprise"],
    weight: 5,
    aiActArticle: "Article 48 - Marquage CE",
  },

  // ============================================
  // FOURNISSEURS (10 questions)
  // ============================================
  {
    id: "suppliers_ai_inventory",
    category: "suppliers",
    subcategory: "Inventaire",
    question: "Avez-vous identifié tous vos fournisseurs de solutions IA ?",
    type: "single",
    options: [
      { label: "Oui, liste complète et à jour", value: "complete", score: 0 },
      { label: "Oui, liste partielle", value: "partial", score: 2 },
      { label: "Non", value: "no", score: 3 },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 6,
    collectData: "hasSuppliersList",
  },
  {
    id: "suppliers_contract_review",
    category: "suppliers",
    subcategory: "Contrats",
    question: "Vos contrats fournisseurs incluent-ils des clauses AI Act ?",
    type: "single",
    options: [
      { label: "Oui, clauses spécifiques négociées", value: "specific", score: 0 },
      { label: "Non, mais prévu lors des renouvellements", value: "planned", score: 2 },
      { label: "Non", value: "no", score: 3 },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 7,
    aiActArticle: "Article 25 - Chaîne de valeur",
  },
  {
    id: "suppliers_documentation",
    category: "suppliers",
    subcategory: "Documentation",
    question: "Obtenez-vous la documentation technique de vos fournisseurs IA ?",
    type: "single",
    options: [
      { label: "Oui, documentation complète reçue", value: "complete", score: 0 },
      { label: "Oui, documentation partielle", value: "partial", score: 2 },
      { label: "Non, pas demandée ou refusée", value: "no", score: 4 },
    ],
    required: true,
    forPlans: ["pro", "enterprise"],
    weight: 6,
    aiActArticle: "Article 13",
  },
  {
    id: "suppliers_compliance_check",
    category: "suppliers",
    subcategory: "Vérification",
    question: "Vérifiez-vous la conformité AI Act de vos fournisseurs ?",
    type: "single",
    options: [
      { label: "Oui, vérification systématique", value: "systematic", score: 0 },
      { label: "Oui, pour les principaux fournisseurs", value: "main", score: 1 },
      { label: "Non", value: "no", score: 3 },
    ],
    required: true,
    forPlans: ["pro", "enterprise"],
    weight: 6,
  },
  {
    id: "suppliers_gpai_providers",
    category: "suppliers",
    subcategory: "GPAI",
    question: "Utilisez-vous des modèles d'IA à usage général (GPAI) de fournisseurs tiers ?",
    description: "Ex: API OpenAI, Claude, Gemini, Llama, Mistral...",
    type: "single",
    options: [
      { label: "Oui, plusieurs fournisseurs", value: "multiple", score: 2 },
      { label: "Oui, un fournisseur principal", value: "one", score: 1 },
      { label: "Non", value: "no", score: 0 },
    ],
    required: true,
    forPlans: ["starter", "pro", "enterprise"],
    weight: 5,
    aiActArticle: "Article 51-56 - GPAI",
    collectData: "gpaiProviders",
  },
  {
    id: "suppliers_liability",
    category: "suppliers",
    subcategory: "Responsabilité",
    question: "Avez-vous clarifié la répartition des responsabilités avec vos fournisseurs IA ?",
    type: "single",
    options: [
      { label: "Oui, responsabilités définies contractuellement", value: "defined", score: 0 },
      { label: "Partiellement", value: "partial", score: 2 },
      { label: "Non", value: "no", score: 3 },
    ],
    required: true,
    forPlans: ["pro", "enterprise"],
    weight: 6,
    aiActArticle: "Article 25",
  },
];

// Fonction pour obtenir les questions filtrées
export function getFilteredQuestions(
  plan: "starter" | "pro" | "enterprise",
  sector?: string,
  size?: string,
  previousAnswers?: Record<string, string | string[]>
): Question[] {
  return QUESTIONS.filter((q) => {
    // Filtre par plan
    if (!q.forPlans.includes(plan)) return false;
    
    // Filtre par secteur
    if (q.forSectors && q.forSectors.length > 0 && sector) {
      if (!q.forSectors.includes(sector)) return false;
    }
    
    // Filtre par taille
    if (q.forSizes && q.forSizes.length > 0 && size) {
      if (!q.forSizes.includes(size)) return false;
    }
    
    // Filtre par conditions (questions précédentes)
    if (q.conditions && previousAnswers) {
      for (const condition of q.conditions) {
        const answer = previousAnswers[condition.questionId];
        if (!answer) return false;
        
        if (Array.isArray(answer)) {
          if (!condition.values.some(v => answer.includes(v))) return false;
        } else {
          if (!condition.values.includes(answer)) return false;
        }
      }
    }
    
    return true;
  });
}

// Nombre de questions par plan
export const QUESTIONS_COUNT = {
  starter: QUESTIONS.filter(q => q.forPlans.includes("starter")).length,
  pro: QUESTIONS.filter(q => q.forPlans.includes("pro")).length,
  enterprise: QUESTIONS.filter(q => q.forPlans.includes("enterprise")).length,
};
